# Generated by Django 5.2.10 on 2026-01-15 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('use_ai', models.BooleanField(default=True)),
                ('extract_artifacts', models.BooleanField(default=True)),
                ('index_for_search', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cases.evidence')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('file', 'File'), ('email', 'Email'), ('chat', 'Chat Message'), ('call_log', 'Call Log'), ('browser_history', 'Browser History'), ('registry', 'System Registry'), ('log', 'System Log'), ('location', 'Location Data'), ('media', 'Media (Image/Video)')], max_length=50)),
                ('name', models.CharField(max_length=512)),
                ('original_path', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ai_labels', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='analysis.analysis')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='cases.evidence')),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='analysis_ar_type_281117_idx'), models.Index(fields=['is_suspicious'], name='analysis_ar_is_susp_10e0dc_idx'), models.Index(fields=['timestamp'], name='analysis_ar_timesta_cc5f17_idx')],
            },
        ),
    ]
