# Generated by Django 5.2.10 on 2026-01-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='type',
            field=models.CharField(choices=[('basic_metadata', 'Basic Metadata Extractor'), ('deep_file', 'Deep File Content Analysis'), ('ai_copilot', 'AI Copilot Semantic Search')], default='basic_metadata', max_length=50),
        ),
        migrations.AddField(
            model_name='artifact',
            name='file_system_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='artifact',
            name='raw_hex_preview',
            field=models.TextField(blank=True, help_text='Hex dump of relevant bytes'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('email', 'Email'), ('chat', 'Chat Message'), ('call_log', 'Call Log'), ('browser_history', 'Browser History'), ('registry', 'System Registry'), ('log', 'System Log'), ('location', 'Location Data'), ('media', 'Media (Image/Video)'), ('browser_cookie', 'Browser Cookie'), ('browser_download', 'Browser Download'), ('windows_lnk', 'Windows LNK Link File'), ('prefetch_file', 'Windows Prefetch'), ('shellbag', 'Windows Shellbag'), ('usn_journal', 'NTFS USN Journal Entry'), ('metadata_exif', 'EXIF Metadata'), ('metadata_ole', 'OLE/Document Metadata'), ('network_flow', 'Network Connection')], max_length=50),
        ),
    ]
