# Generated by Django 5.2.10 on 2026-01-15 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('disk_physical', 'Physical Disk (DD)'), ('disk_expert', 'Expert Witness (E01)'), ('memory_dump', 'Memory Dump'), ('mobile_ios', 'iOS Extraction'), ('mobile_android', 'Android Extraction'), ('cloud_s3', 'Cloud S3 Capture'), ('network_pcap', 'Network PCAP'), ('remote_agent', 'Remote Agent Collection')], max_length=50)),
                ('source_path', models.CharField(max_length=1024)),
                ('destination_path', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('current_speed', models.CharField(blank=True, max_length=50)),
                ('calculated_md5', models.CharField(blank=True, max_length=32)),
                ('calculated_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_task', to='cases.evidence')),
            ],
        ),
    ]
