# Generated by Django 5.2.10 on 2026-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitiontask',
            name='source_upload',
            field=models.FileField(blank=True, null=True, upload_to='acquisition_uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='acquisitiontask',
            name='destination_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='acquisitiontask',
            name='source_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='acquisitiontask',
            name='type',
            field=models.CharField(choices=[('disk_physical', 'Physical Disk (DD)'), ('disk_expert', 'Expert Witness (E01)'), ('memory_dump', 'Memory Dump'), ('mobile_ios', 'iOS Extraction'), ('mobile_android', 'Android Extraction'), ('cloud_s3', 'Cloud S3 Capture'), ('network_pcap', 'Network PCAP'), ('remote_agent', 'Remote Agent Collection'), ('file_upload', 'Evidence File Upload')], max_length=50),
        ),
    ]
