# Generated by Django 5.2.10 on 2026-01-15 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('system', 'System File'), ('application', 'Application Data'), ('network', 'Network Activity'), ('manual', 'Manual Entry')], max_length=20)),
                ('description', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('is_gap_flagged', models.BooleanField(default=False)),
                ('artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='analysis.artifact')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case')),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.evidence')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='timeline_ti_timesta_d5b80f_idx'), models.Index(fields=['event_type'], name='timeline_ti_event_t_0e25e4_idx')],
            },
        ),
    ]
